### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Connor-fire** [SNTSVV/Extended-DM2-Instrumenter#1]
When I use the command "./gradlew build" to build the project, the following error is reported:

`Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.soot-oss:soot:4.3.0-SNAPSHOT.
     Required by:
         project : > de.tud.sse:soot-infoflow-android:2.8 > de.tud.sse:soot-infoflow:2.8
      > Could not resolve org.soot-oss:soot:4.3.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/org/soot-oss/soot/4.3.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/org/soot-oss/soot/4.3.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/org/soot-oss/soot/4.3.0-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Repository version policy: RELEASE does not allow metadata in path: org/soot-oss/soot/4.3.0-SNAPSHOT/maven-metadata.xml`

It seems that the project is trying to resolve a dependency org.soot-oss:soot:4.3.0-SNAPSHOT but it’s unable to do so because the repository https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/ does not allow metadata in the path org/soot-oss/soot/4.3.0-SNAPSHOT/maven-metadata.xml due to its version policy being RELEASE .

Looking forward to your reply.

**Comment by chanhduc** [comment]
Hi @Connor-fire,

It is true that the dependency is not resolvable anymore. I updated it with the new dependency. Please check out the new version.

Thanks.

**Comment by Connor-fire** [comment]
Thanks for your help
